import { User, Bill, Expense, RentPlan, ShopItem, Redemption, Payment } from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'tenant-1',
    email: 'tenant@example.com',
    name: 'John Doe',
    role: 'tenant',
    points: 250,
    landlordId: 'landlord-1',
  },
  {
    id: 'demo-tenant',
    email: 'demo@example.com',
    name: 'Demo Tenant',
    role: 'tenant',
    points: 350,
    landlordId: 'landlord-1',
  },
  {
    id: 'tenant-2',
    email: 'sarah.johnson@example.com',
    name: 'Sarah Johnson',
    role: 'tenant',
    points: 420,
    landlordId: 'landlord-1',
  },
  {
    id: 'tenant-3',
    email: 'michael.chen@example.com',
    name: 'Michael Chen',
    role: 'tenant',
    points: 185,
    landlordId: 'landlord-1',
  },
  {
    id: 'tenant-4',
    email: 'emily.rodriguez@example.com',
    name: 'Emily Rodriguez',
    role: 'tenant',
    points: 310,
    landlordId: 'landlord-1',
  },
  {
    id: 'tenant-5',
    email: 'david.kim@example.com',
    name: 'David Kim',
    role: 'tenant',
    points: 95,
    landlordId: 'landlord-1',
  },
  {
    id: 'tenant-6',
    email: 'lisa.patel@example.com',
    name: 'Lisa Patel',
    role: 'tenant',
    points: 275,
    landlordId: 'landlord-1',
  },
  {
    id: 'tenant-7',
    email: 'james.wilson@example.com',
    name: 'James Wilson',
    role: 'tenant',
    points: 540,
    landlordId: 'landlord-1',
  },
  {
    id: 'landlord-1',
    email: 'landlord@example.com',
    name: 'Jane Smith',
    role: 'landlord',
  },
];

// Mock Bills - Enhanced with more data for demo tenant
export const mockBills: Bill[] = [
  // Tenant 1 bills
  {
    id: 'bill-1',
    tenantId: 'tenant-1',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1500,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 28).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-2',
    tenantId: 'tenant-1',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 150,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 4).toISOString(),
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-3',
    tenantId: 'tenant-1',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 80,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  {
    id: 'bill-4',
    tenantId: 'tenant-1',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1500,
    dueDate: new Date(2025, 11, 1).toISOString(),
    isPaid: false,
    description: 'Monthly Rent - December 2025',
  },
  // Demo tenant bills - fully populated
  {
    id: 'demo-bill-1',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1800,
    dueDate: new Date(2025, 9, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 8, 28).toISOString(),
    description: 'Monthly Rent - October 2025',
  },
  {
    id: 'demo-bill-2',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 165,
    dueDate: new Date(2025, 9, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 3).toISOString(),
    description: 'Utilities - October 2025',
  },
  {
    id: 'demo-bill-3',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 90,
    dueDate: new Date(2025, 9, 10).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 9).toISOString(),
    description: 'Internet Service - October 2025',
  },
  {
    id: 'demo-bill-4',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1800,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 30).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'demo-bill-5',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 158,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 4).toISOString(),
    description: 'Utilities - November 2025',
  },
  {
    id: 'demo-bill-6',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 90,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  {
    id: 'demo-bill-7',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1800,
    dueDate: new Date(2025, 11, 1).toISOString(),
    isPaid: false,
    description: 'Monthly Rent - December 2025',
  },
  {
    id: 'demo-bill-8',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    type: 'other',
    amount: 250,
    dueDate: new Date(2025, 10, 15).toISOString(),
    isPaid: false,
    description: 'Parking Fee - November 2025',
  },
  // Sarah Johnson bills (tenant-2)
  {
    id: 'bill-5',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 2000,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 29).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-6',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 180,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 3).toISOString(),
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-7',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 95,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  {
    id: 'bill-8',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 2000,
    dueDate: new Date(2025, 11, 1).toISOString(),
    isPaid: false,
    description: 'Monthly Rent - December 2025',
  },
  // Michael Chen bills (tenant-3)
  {
    id: 'bill-9',
    tenantId: 'tenant-3',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1350,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 2).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-10',
    tenantId: 'tenant-3',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 125,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: false,
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-11',
    tenantId: 'tenant-3',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 75,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  // Emily Rodriguez bills (tenant-4)
  {
    id: 'bill-12',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1750,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 30).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-13',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 145,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 5).toISOString(),
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-14',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 85,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  {
    id: 'bill-15',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    type: 'other',
    amount: 200,
    dueDate: new Date(2025, 10, 20).toISOString(),
    isPaid: false,
    description: 'Maintenance Fee - November 2025',
  },
  // David Kim bills (tenant-5)
  {
    id: 'bill-16',
    tenantId: 'tenant-5',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1600,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: false,
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-17',
    tenantId: 'tenant-5',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 135,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: false,
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-18',
    tenantId: 'tenant-5',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 80,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  // Lisa Patel bills (tenant-6)
  {
    id: 'bill-19',
    tenantId: 'tenant-6',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1900,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 28).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-20',
    tenantId: 'tenant-6',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 170,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 4).toISOString(),
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-21',
    tenantId: 'tenant-6',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 90,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: false,
    description: 'Internet Service - November 2025',
  },
  {
    id: 'bill-22',
    tenantId: 'tenant-6',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1900,
    dueDate: new Date(2025, 11, 1).toISOString(),
    isPaid: false,
    description: 'Monthly Rent - December 2025',
  },
  // James Wilson bills (tenant-7)
  {
    id: 'bill-23',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 2200,
    dueDate: new Date(2025, 10, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 27).toISOString(),
    description: 'Monthly Rent - November 2025',
  },
  {
    id: 'bill-24',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    type: 'utilities',
    amount: 195,
    dueDate: new Date(2025, 10, 5).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 2).toISOString(),
    description: 'Utilities - November 2025',
  },
  {
    id: 'bill-25',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    type: 'internet',
    amount: 100,
    dueDate: new Date(2025, 10, 10).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 9).toISOString(),
    description: 'Internet Service - November 2025',
  },
  {
    id: 'bill-26',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    type: 'other',
    amount: 150,
    dueDate: new Date(2025, 10, 15).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 10, 14).toISOString(),
    description: 'Storage Unit - November 2025',
  },
  {
    id: 'bill-27',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 2200,
    dueDate: new Date(2025, 11, 1).toISOString(),
    isPaid: false,
    description: 'Monthly Rent - December 2025',
  },
  // Historical bills for previous months
  {
    id: 'bill-28',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 2000,
    dueDate: new Date(2025, 9, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 8, 30).toISOString(),
    description: 'Monthly Rent - October 2025',
  },
  {
    id: 'bill-29',
    tenantId: 'tenant-3',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1350,
    dueDate: new Date(2025, 9, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 9, 1).toISOString(),
    description: 'Monthly Rent - October 2025',
  },
  {
    id: 'bill-30',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1750,
    dueDate: new Date(2025, 9, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 8, 29).toISOString(),
    description: 'Monthly Rent - October 2025',
  },
  {
    id: 'bill-31',
    tenantId: 'tenant-6',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 1900,
    dueDate: new Date(2025, 9, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 8, 31).toISOString(),
    description: 'Monthly Rent - October 2025',
  },
  {
    id: 'bill-32',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    type: 'rent',
    amount: 2200,
    dueDate: new Date(2025, 9, 1).toISOString(),
    isPaid: true,
    paidDate: new Date(2025, 8, 28).toISOString(),
    description: 'Monthly Rent - October 2025',
  },
];

// Mock Expenses - Enhanced with more data for demo tenant
export const mockExpenses: Expense[] = [
  // Tenant 1 expenses
  {
    id: 'expense-1',
    tenantId: 'tenant-1',
    category: 'Food',
    amount: 85.50,
    date: new Date(2025, 10, 5).toISOString(),
    description: 'Grocery shopping',
  },
  {
    id: 'expense-2',
    tenantId: 'tenant-1',
    category: 'Transportation',
    amount: 45.00,
    date: new Date(2025, 10, 6).toISOString(),
    description: 'Gas for car',
  },
  {
    id: 'expense-3',
    tenantId: 'tenant-1',
    category: 'Entertainment',
    amount: 35.00,
    date: new Date(2025, 10, 7).toISOString(),
    description: 'Movie tickets',
  },
  {
    id: 'expense-4',
    tenantId: 'tenant-1',
    category: 'Food',
    amount: 120.00,
    date: new Date(2025, 10, 3).toISOString(),
    description: 'Restaurant dinner',
  },
  {
    id: 'expense-5',
    tenantId: 'tenant-1',
    category: 'Healthcare',
    amount: 65.00,
    date: new Date(2025, 10, 2).toISOString(),
    description: 'Pharmacy',
  },
  // Demo tenant expenses - fully populated
  {
    id: 'demo-expense-1',
    tenantId: 'demo-tenant',
    category: 'Food',
    amount: 125.75,
    date: new Date(2025, 10, 1).toISOString(),
    description: 'Weekly groceries at Whole Foods',
  },
  {
    id: 'demo-expense-2',
    tenantId: 'demo-tenant',
    category: 'Transportation',
    amount: 65.00,
    date: new Date(2025, 10, 2).toISOString(),
    description: 'Gas and car wash',
  },
  {
    id: 'demo-expense-3',
    tenantId: 'demo-tenant',
    category: 'Entertainment',
    amount: 45.50,
    date: new Date(2025, 10, 3).toISOString(),
    description: 'Movie night with friends',
  },
  {
    id: 'demo-expense-4',
    tenantId: 'demo-tenant',
    category: 'Food',
    amount: 89.20,
    date: new Date(2025, 10, 4).toISOString(),
    description: 'Lunch and dinner out',
  },
  {
    id: 'demo-expense-5',
    tenantId: 'demo-tenant',
    category: 'Healthcare',
    amount: 45.00,
    date: new Date(2025, 10, 5).toISOString(),
    description: 'Prescription medications',
  },
  {
    id: 'demo-expense-6',
    tenantId: 'demo-tenant',
    category: 'Shopping',
    amount: 156.30,
    date: new Date(2025, 10, 5).toISOString(),
    description: 'Clothing and accessories',
  },
  {
    id: 'demo-expense-7',
    tenantId: 'demo-tenant',
    category: 'Food',
    amount: 98.45,
    date: new Date(2025, 10, 6).toISOString(),
    description: 'Grocery shopping',
  },
  {
    id: 'demo-expense-8',
    tenantId: 'demo-tenant',
    category: 'Transportation',
    amount: 28.00,
    date: new Date(2025, 10, 6).toISOString(),
    description: 'Uber rides',
  },
  {
    id: 'demo-expense-9',
    tenantId: 'demo-tenant',
    category: 'Entertainment',
    amount: 75.00,
    date: new Date(2025, 10, 7).toISOString(),
    description: 'Concert tickets',
  },
  {
    id: 'demo-expense-10',
    tenantId: 'demo-tenant',
    category: 'Food',
    amount: 142.50,
    date: new Date(2025, 10, 7).toISOString(),
    description: 'Weekend brunch',
  },
  {
    id: 'demo-expense-11',
    tenantId: 'demo-tenant',
    category: 'Utilities',
    amount: 55.00,
    date: new Date(2025, 9, 15).toISOString(),
    description: 'Phone bill',
  },
  {
    id: 'demo-expense-12',
    tenantId: 'demo-tenant',
    category: 'Food',
    amount: 210.00,
    date: new Date(2025, 9, 20).toISOString(),
    description: 'Costco shopping',
  },
  {
    id: 'demo-expense-13',
    tenantId: 'demo-tenant',
    category: 'Transportation',
    amount: 70.00,
    date: new Date(2025, 9, 22).toISOString(),
    description: 'Gas for the month',
  },
  {
    id: 'demo-expense-14',
    tenantId: 'demo-tenant',
    category: 'Entertainment',
    amount: 120.00,
    date: new Date(2025, 9, 25).toISOString(),
    description: 'Streaming services subscription',
  },
];

// Mock Rent Plans - Enhanced with demo tenant data
export const mockRentPlans: RentPlan[] = [
  {
    id: 'plan-1',
    tenantId: 'tenant-1',
    landlordId: 'landlord-1',
    monthlyRent: 1500,
    deposit: 3000,
    duration: 12,
    status: 'approved',
    proposedDate: new Date(2025, 9, 15).toISOString(),
    reviewedDate: new Date(2025, 9, 16).toISOString(),
  },
  {
    id: 'demo-plan-1',
    tenantId: 'demo-tenant',
    landlordId: 'landlord-1',
    monthlyRent: 1800,
    deposit: 3600,
    duration: 12,
    status: 'approved',
    proposedDate: new Date(2025, 8, 1).toISOString(),
    reviewedDate: new Date(2025, 8, 3).toISOString(),
  },
  {
    id: 'plan-2',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    monthlyRent: 2000,
    deposit: 4000,
    duration: 12,
    status: 'approved',
    proposedDate: new Date(2025, 7, 10).toISOString(),
    reviewedDate: new Date(2025, 7, 12).toISOString(),
  },
  {
    id: 'plan-3',
    tenantId: 'tenant-3',
    landlordId: 'landlord-1',
    monthlyRent: 1350,
    deposit: 2700,
    duration: 6,
    status: 'approved',
    proposedDate: new Date(2025, 8, 20).toISOString(),
    reviewedDate: new Date(2025, 8, 21).toISOString(),
  },
  {
    id: 'plan-4',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    monthlyRent: 1750,
    deposit: 3500,
    duration: 12,
    status: 'approved',
    proposedDate: new Date(2025, 6, 5).toISOString(),
    reviewedDate: new Date(2025, 6, 7).toISOString(),
  },
  {
    id: 'plan-5',
    tenantId: 'tenant-5',
    landlordId: 'landlord-1',
    monthlyRent: 1600,
    deposit: 3200,
    duration: 12,
    status: 'pending',
    proposedDate: new Date(2025, 10, 3).toISOString(),
  },
  {
    id: 'plan-6',
    tenantId: 'tenant-6',
    landlordId: 'landlord-1',
    monthlyRent: 1900,
    deposit: 3800,
    duration: 12,
    status: 'approved',
    proposedDate: new Date(2025, 7, 15).toISOString(),
    reviewedDate: new Date(2025, 7, 16).toISOString(),
  },
  {
    id: 'plan-7',
    tenantId: 'tenant-7',
    landlordId: 'landlord-1',
    monthlyRent: 2200,
    deposit: 4400,
    duration: 24,
    status: 'approved',
    proposedDate: new Date(2025, 5, 1).toISOString(),
    reviewedDate: new Date(2025, 5, 3).toISOString(),
  },
  {
    id: 'plan-8',
    tenantId: 'tenant-3',
    landlordId: 'landlord-1',
    monthlyRent: 1400,
    deposit: 2800,
    duration: 6,
    status: 'pending',
    proposedDate: new Date(2025, 10, 5).toISOString(),
  },
  {
    id: 'plan-9',
    tenantId: 'tenant-2',
    landlordId: 'landlord-1',
    monthlyRent: 2100,
    deposit: 4200,
    duration: 12,
    status: 'pending',
    proposedDate: new Date(2025, 10, 6).toISOString(),
  },
  {
    id: 'plan-10',
    tenantId: 'tenant-1',
    landlordId: 'landlord-1',
    monthlyRent: 1550,
    deposit: 3100,
    duration: 6,
    status: 'rejected',
    proposedDate: new Date(2025, 10, 1).toISOString(),
    reviewedDate: new Date(2025, 10, 2).toISOString(),
  },
  {
    id: 'plan-11',
    tenantId: 'tenant-4',
    landlordId: 'landlord-1',
    monthlyRent: 1650,
    deposit: 3300,
    duration: 6,
    status: 'rejected',
    proposedDate: new Date(2025, 9, 20).toISOString(),
    reviewedDate: new Date(2025, 9, 22).toISOString(),
  },
];

// Mock Shop Items
export const mockShopItems: ShopItem[] = [
  {
    id: 'item-1',
    name: '$25 Amazon Gift Card',
    description: 'Redeem for a $25 Amazon gift card',
    pointCost: 100,
    imageUrl: '🎁',
  },
  {
    id: 'item-2',
    name: 'Free Cleaning Service',
    description: 'Professional apartment cleaning service',
    pointCost: 200,
    imageUrl: '🧹',
  },
  {
    id: 'item-3',
    name: '$50 Grocery Voucher',
    description: 'Use at major grocery stores',
    pointCost: 150,
    imageUrl: '🛒',
  },
  {
    id: 'item-4',
    name: 'Movie Night Package',
    description: '2 movie tickets + popcorn',
    pointCost: 80,
    imageUrl: '🎬',
  },
  {
    id: 'item-5',
    name: '$100 Uber Credit',
    description: 'Travel credit for Uber rides',
    pointCost: 250,
    imageUrl: '🚗',
  },
  {
    id: 'item-6',
    name: 'Gym Membership (1 Month)',
    description: 'Access to local fitness center',
    pointCost: 120,
    imageUrl: '💪',
  },
  {
    id: 'item-7',
    name: '$10 Starbucks Gift Card',
    description: 'Enjoy your favorite coffee',
    pointCost: 50,
    imageUrl: '☕',
  },
  {
    id: 'item-8',
    name: 'Spa Day Package',
    description: 'Relaxing spa treatment',
    pointCost: 300,
    imageUrl: '💆',
  },
];

// Mock Redemptions - Enhanced with demo tenant data
export const mockRedemptions: Redemption[] = [
  {
    id: 'redemption-1',
    tenantId: 'tenant-1',
    itemId: 'item-4',
    itemName: 'Movie Night Package',
    pointsSpent: 80,
    date: new Date(2025, 9, 20).toISOString(),
  },
  {
    id: 'demo-redemption-1',
    tenantId: 'demo-tenant',
    itemId: 'item-4',
    itemName: 'Movie Night Package',
    pointsSpent: 80,
    date: new Date(2025, 9, 15).toISOString(),
  },
  {
    id: 'demo-redemption-2',
    tenantId: 'demo-tenant',
    itemId: 'item-1',
    itemName: '$25 Amazon Gift Card',
    pointsSpent: 100,
    date: new Date(2025, 9, 22).toISOString(),
  },
  {
    id: 'demo-redemption-3',
    tenantId: 'demo-tenant',
    itemId: 'item-7',
    itemName: '$10 Starbucks Gift Card',
    pointsSpent: 50,
    date: new Date(2025, 10, 2).toISOString(),
  },
];

// Mock Payments - Payment history for tracking points
export const mockPayments: Payment[] = [
  {
    id: 'payment-1',
    tenantId: 'demo-tenant',
    billId: 'demo-bill-1',
    amount: 1800,
    date: new Date(2025, 8, 28).toISOString(),
    isOnTime: true,
    pointsEarned: 50,
  },
  {
    id: 'payment-2',
    tenantId: 'demo-tenant',
    billId: 'demo-bill-2',
    amount: 165,
    date: new Date(2025, 9, 3).toISOString(),
    isOnTime: true,
    pointsEarned: 25,
  },
  {
    id: 'payment-3',
    tenantId: 'demo-tenant',
    billId: 'demo-bill-3',
    amount: 90,
    date: new Date(2025, 9, 9).toISOString(),
    isOnTime: true,
    pointsEarned: 15,
  },
  {
    id: 'payment-4',
    tenantId: 'demo-tenant',
    billId: 'demo-bill-4',
    amount: 1800,
    date: new Date(2025, 9, 30).toISOString(),
    isOnTime: true,
    pointsEarned: 50,
  },
  {
    id: 'payment-5',
    tenantId: 'demo-tenant',
    billId: 'demo-bill-5',
    amount: 158,
    date: new Date(2025, 10, 4).toISOString(),
    isOnTime: true,
    pointsEarned: 25,
  },
  {
    id: 'payment-6',
    tenantId: 'tenant-1',
    billId: 'bill-1',
    amount: 1500,
    date: new Date(2025, 9, 28).toISOString(),
    isOnTime: true,
    pointsEarned: 45,
  },
  {
    id: 'payment-7',
    tenantId: 'tenant-1',
    billId: 'bill-2',
    amount: 150,
    date: new Date(2025, 10, 4).toISOString(),
    isOnTime: true,
    pointsEarned: 20,
  },
  {
    id: 'payment-8',
    tenantId: 'tenant-2',
    billId: 'bill-5',
    amount: 2000,
    date: new Date(2025, 9, 29).toISOString(),
    isOnTime: true,
    pointsEarned: 55,
  },
  {
    id: 'payment-9',
    tenantId: 'tenant-2',
    billId: 'bill-6',
    amount: 180,
    date: new Date(2025, 10, 3).toISOString(),
    isOnTime: true,
    pointsEarned: 25,
  },
  {
    id: 'payment-10',
    tenantId: 'tenant-2',
    billId: 'bill-28',
    amount: 2000,
    date: new Date(2025, 8, 30).toISOString(),
    isOnTime: true,
    pointsEarned: 55,
  },
  {
    id: 'payment-11',
    tenantId: 'tenant-3',
    billId: 'bill-9',
    amount: 1350,
    date: new Date(2025, 10, 2).toISOString(),
    isOnTime: false,
    pointsEarned: 0,
  },
  {
    id: 'payment-12',
    tenantId: 'tenant-3',
    billId: 'bill-29',
    amount: 1350,
    date: new Date(2025, 9, 1).toISOString(),
    isOnTime: true,
    pointsEarned: 40,
  },
  {
    id: 'payment-13',
    tenantId: 'tenant-4',
    billId: 'bill-12',
    amount: 1750,
    date: new Date(2025, 9, 30).toISOString(),
    isOnTime: true,
    pointsEarned: 50,
  },
  {
    id: 'payment-14',
    tenantId: 'tenant-4',
    billId: 'bill-13',
    amount: 145,
    date: new Date(2025, 10, 5).toISOString(),
    isOnTime: true,
    pointsEarned: 20,
  },
  {
    id: 'payment-15',
    tenantId: 'tenant-4',
    billId: 'bill-30',
    amount: 1750,
    date: new Date(2025, 8, 29).toISOString(),
    isOnTime: true,
    pointsEarned: 50,
  },
  {
    id: 'payment-16',
    tenantId: 'tenant-6',
    billId: 'bill-19',
    amount: 1900,
    date: new Date(2025, 9, 28).toISOString(),
    isOnTime: true,
    pointsEarned: 52,
  },
  {
    id: 'payment-17',
    tenantId: 'tenant-6',
    billId: 'bill-20',
    amount: 170,
    date: new Date(2025, 10, 4).toISOString(),
    isOnTime: true,
    pointsEarned: 23,
  },
  {
    id: 'payment-18',
    tenantId: 'tenant-6',
    billId: 'bill-31',
    amount: 1900,
    date: new Date(2025, 8, 31).toISOString(),
    isOnTime: true,
    pointsEarned: 52,
  },
  {
    id: 'payment-19',
    tenantId: 'tenant-7',
    billId: 'bill-23',
    amount: 2200,
    date: new Date(2025, 9, 27).toISOString(),
    isOnTime: true,
    pointsEarned: 60,
  },
  {
    id: 'payment-20',
    tenantId: 'tenant-7',
    billId: 'bill-24',
    amount: 195,
    date: new Date(2025, 10, 2).toISOString(),
    isOnTime: true,
    pointsEarned: 27,
  },
  {
    id: 'payment-21',
    tenantId: 'tenant-7',
    billId: 'bill-25',
    amount: 100,
    date: new Date(2025, 10, 9).toISOString(),
    isOnTime: true,
    pointsEarned: 15,
  },
  {
    id: 'payment-22',
    tenantId: 'tenant-7',
    billId: 'bill-26',
    amount: 150,
    date: new Date(2025, 10, 14).toISOString(),
    isOnTime: true,
    pointsEarned: 20,
  },
  {
    id: 'payment-23',
    tenantId: 'tenant-7',
    billId: 'bill-32',
    amount: 2200,
    date: new Date(2025, 8, 28).toISOString(),
    isOnTime: true,
    pointsEarned: 60,
  },
];

// Helper to get current user from localStorage
export function getCurrentUser(): User | null {
  if (typeof window === 'undefined') return null;
  const storedUser = localStorage.getItem('user');
  return storedUser ? JSON.parse(storedUser) : null;
}

// Helper to set current user
export function setCurrentUser(user: User): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem('user', JSON.stringify(user));
  localStorage.setItem('token', 'mock-jwt-token');
}

// Helper to clear current user
export function clearCurrentUser(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem('user');
  localStorage.removeItem('token');
}
